In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
from sklearn.datasets import make_blobs

In [5]:
make_blobs

<function sklearn.datasets._samples_generator.make_blobs(n_samples=100, n_features=2, *, centers=None, cluster_std=1.0, center_box=(-10.0, 10.0), shuffle=True, random_state=None, return_centers=False)>

In [7]:
X,y = make_blobs(n_samples=100, n_features=2,  centers=4, cluster_std=1.5,  random_state=4)

In [8]:
X.shape

(100, 2)

In [9]:
X

array([[  2.93285385,  -8.62723217],
       [  8.92629175,   2.13941283],
       [  8.0371343 ,   4.71761689],
       [  4.40892954,  -4.40262978],
       [  7.68222071,   2.20139951],
       [ 11.87913335,  -0.72457325],
       [  9.34637193, -11.44263045],
       [  7.62489892,   1.70952466],
       [ 10.26860131,   0.81266459],
       [ 12.67563711,   1.53608781],
       [  4.07647215,  -6.03899635],
       [  2.1434758 ,  -7.43064551],
       [  4.56666374,  -3.07961233],
       [  7.8661093 ,   1.02629409],
       [ 10.21835548,   4.74698819],
       [ 11.52356734,   4.21448182],
       [ 11.36141513,   3.32485307],
       [  8.28557731,   4.56543595],
       [  9.83897183,  -0.77656997],
       [  7.60537239,   1.47114071],
       [  6.32288786,  -5.9889826 ],
       [ 11.95135091,  -9.77343661],
       [ 10.42560919,   1.01384833],
       [  4.12695976,  -5.35965466],
       [  8.43026586,   3.26511398],
       [  5.88402429,   3.38479434],
       [  5.51593604,  -6.29118556],
 

In [10]:
y.shape

(100,)

In [13]:
from collections import Counter

In [14]:
Counter(y)

Counter({2: 25, 0: 25, 1: 25, 3: 25})

In [15]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,train_size=0.80)

In [19]:
X_train.shape

(80, 2)

In [20]:
y_train.shape

(80,)

In [21]:
X_test.shape

(20, 2)

In [24]:
from sklearn.neighbors import KNeighborsClassifier

In [25]:
knn = KNeighborsClassifier()

In [28]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [29]:
y_pred = knn.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score

In [31]:
accuracy_score(y_test,y_pred)

0.9

In [32]:
y_pred

array([2, 0, 1, 1, 2, 3, 1, 2, 3, 3, 1, 3, 1, 0, 0, 2, 0, 1, 2, 0])

In [36]:
y_test

array([2, 1, 1, 1, 2, 3, 1, 2, 3, 3, 1, 3, 1, 0, 0, 2, 0, 0, 2, 0])

In [33]:
from sklearn.metrics import classification_report

In [35]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.80      0.80         5
           1       0.83      0.83      0.83         6
           2       1.00      1.00      1.00         5
           3       1.00      1.00      1.00         4

    accuracy                           0.90        20
   macro avg       0.91      0.91      0.91        20
weighted avg       0.90      0.90      0.90        20

