# Loading the Data

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

titanic = pd.read_csv("train.csv")

titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# Pre-Processing

# 1. Drop features that do not seem to add any value to our model

In [5]:
titanic.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

In [6]:
titanic

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [7]:
#titanic['Embarked'] =titanic['Embarked'].astype('category').cat.codes


In [8]:
titanic

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

# 2. Create categorical dummies for the embarkment ports

In [9]:
ports = pd.get_dummies(titanic.Embarked, prefix='Embarked')
ports.head()

Embarked_C  Embarked_Q  Embarked_S
0           0           0           1
1           1           0           0
2           0           0           1
3           0           0           1
4           0           0           1

In [10]:
titanic = titanic.join(ports)
titanic.drop(['Embarked'], axis=1, inplace=True)

In [11]:
titanic

Survived  Pclass     Sex   Age  SibSp  Parch     Fare  Embarked_C  \
0           0       3    male  22.0      1      0   7.2500           0   
1           1       1  female  38.0      1      0  71.2833           1   
2           1       3  female  26.0      0      0   7.9250           0   
3           1       1  female  35.0      1      0  53.1000           0   
4           0       3    male  35.0      0      0   8.0500           0   
..        ...     ...     ...   ...    ...    ...      ...         ...   
886         0       2    male  27.0      0      0  13.0000           0   
887         1       1  female  19.0      0      0  30.0000           0   
888         0       3  female   NaN      1      2  23.4500           0   
889         1       1    male  26.0      0      0  30.0000           1   
890         0       3    male  32.0      0      0   7.7500           0   

     Embarked_Q  Embarked_S  
0             0           1  
1             0           0  
2             0           1  
3             0           1  
4             0           1  
..          ...         ...  
886           0           1  
887           0           1  
888           0           1  
889           0           0  
890           1           0  

[891 rows x 10 columns]

# 3. Transform gender names to binaries

In [12]:
titanic.Sex = titanic.Sex.map({'male': 0, 'female': 1})

In [13]:
titanic

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  \
0           0       3    0  22.0      1      0   7.2500           0   
1           1       1    1  38.0      1      0  71.2833           1   
2           1       3    1  26.0      0      0   7.9250           0   
3           1       1    1  35.0      1      0  53.1000           0   
4           0       3    0  35.0      0      0   8.0500           0   
..        ...     ...  ...   ...    ...    ...      ...         ...   
886         0       2    0  27.0      0      0  13.0000           0   
887         1       1    1  19.0      0      0  30.0000           0   
888         0       3    1   NaN      1      2  23.4500           0   
889         1       1    0  26.0      0      0  30.0000           1   
890         0       3    0  32.0      0      0   7.7500           0   

     Embarked_Q  Embarked_S  
0             0           1  
1             0           0  
2             0           1  
3             0           1  
4             0           1  
..          ...         ...  
886           0           1  
887           0           1  
888           0           1  
889           0           0  
890           1           0  

[891 rows x 10 columns]

# 4. Replace missing values

In [14]:
titanic[pd.isnull(titanic).any(axis=1)]

Survived  Pclass  Sex  Age  SibSp  Parch     Fare  Embarked_C  \
5           0       3    0  NaN      0      0   8.4583           0   
17          1       2    0  NaN      0      0  13.0000           0   
19          1       3    1  NaN      0      0   7.2250           1   
26          0       3    0  NaN      0      0   7.2250           1   
28          1       3    1  NaN      0      0   7.8792           0   
..        ...     ...  ...  ...    ...    ...      ...         ...   
859         0       3    0  NaN      0      0   7.2292           1   
863         0       3    1  NaN      8      2  69.5500           0   
868         0       3    0  NaN      0      0   9.5000           0   
878         0       3    0  NaN      0      0   7.8958           0   
888         0       3    1  NaN      1      2  23.4500           0   

     Embarked_Q  Embarked_S  
5             1           0  
17            0           1  
19            0           0  
26            0           0  
28            1           0  
..          ...         ...  
859           0           0  
863           0           1  
868           0           1  
878           0           1  
888           0           1  

[177 rows x 10 columns]

In [15]:
titanic.isnull().sum()

Survived        0
Pclass          0
Sex             0
Age           177
SibSp           0
Parch           0
Fare            0
Embarked_C      0
Embarked_Q      0
Embarked_S      0
dtype: int64

In [16]:
titanic.Age.fillna(titanic.Age.mean(), inplace=True)

In [17]:
titanic.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [34]:
X = titanic[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked_C', 'Embarked_Q', 'Embarked_S']]

In [35]:
y = titanic['Survived']

In [36]:
X.head(10)

Pclass  Sex        Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0       3    0  22.000000      1      0   7.2500           0           0   
1       1    1  38.000000      1      0  71.2833           1           0   
2       3    1  26.000000      0      0   7.9250           0           0   
3       1    1  35.000000      1      0  53.1000           0           0   
4       3    0  35.000000      0      0   8.0500           0           0   
5       3    0  29.699118      0      0   8.4583           0           1   
6       1    0  54.000000      0      0  51.8625           0           0   
7       3    0   2.000000      3      1  21.0750           0           0   
8       3    1  27.000000      0      2  11.1333           0           0   
9       2    1  14.000000      1      0  30.0708           1           0   

   Embarked_S  
0           1  
1           0  
2           1  
3           1  
4           1  
5           0  
6           1  
7           1  
8           1  
9           0

# TRAIN TEST SPLIT

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=123)

In [38]:
X_train.head(3)

Pclass  Sex   Age  SibSp  Parch      Fare  Embarked_C  Embarked_Q  \
660       1    0  50.0      2      0  133.6500           0           0   
852       3    1   9.0      1      1   15.2458           1           0   
703       3    0  25.0      0      0    7.7417           0           1   

     Embarked_S  
660           1  
852           0  
703           0

In [39]:
y_train.head(3)

660    1
852    0
703    0
Name: Survived, dtype: int64

In [40]:
model = LogisticRegression()
model.fit(X_train, y_train)

C:\Users\hp\Anaconda0312\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [41]:
y_test

172    1
524    0
452    0
170    0
620    0
      ..
709    1
693    0
738    0
587    1
798    0
Name: Survived, Length: 223, dtype: int64

In [42]:
model.predict(X_test)

array([1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [43]:
y_pred = model.predict(X_test)

In [44]:
y_pred

array([1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [45]:
from sklearn import metrics
metrics.confusion_matrix(y_test,y_pred)

array([[120,  19],
       [ 24,  60]], dtype=int64)

In [46]:

from collections import Counter


In [50]:
y_pred

array([1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [47]:
Counter(y_test)

Counter({1: 84, 0: 139})

In [48]:
Counter(y_pred)

Counter({1: 79, 0: 144})

In [25]:
from sklearn import metrics
y_pred = pd.Series(model.predict(X_test))
y_test = y_test.reset_index(drop=True)
z1 = pd.concat([y_test,y_pred],axis=1)
z1.columns = ['Actual','Predicted']

metrics.accuracy_score(y_test,y_pred)
metrics.precision_score(y_test,y_pred)
metrics.confusion_matrix(y_test,y_pred)

array([[120,  19],
       [ 24,  60]], dtype=int64)

In [28]:
y_pred = model.predict(X_test)

In [29]:
y_pred

array([1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [30]:
y_test

Survived
0           1
1           0
2           0
3           0
4           0
..        ...
218         1
219         0
220         0
221         1
222         0

[223 rows x 1 columns]

In [34]:
y_test

Survived
0           1
1           0
2           0
3           0
4           0
..        ...
218         1
219         0
220         0
221         1
222         0

[223 rows x 1 columns]

In [31]:
from sklearn import metrics

In [32]:
metrics.accuracy_score(y_test,y_pred)

0.8071748878923767

In [33]:
metrics.precision_score(y_test,y_pred)

0.759493670886076

In [34]:
metrics.recall_score(y_test,y_pred)

0.7142857142857143

In [52]:
y_test.shape

(223,)

In [51]:
Counter(y_test)

Counter({1: 84, 0: 139})

In [35]:
metrics.confusion_matrix(y_test,y_pred)

array([[120,  19],
       [ 24,  60]], dtype=int64)

In [ ]:
    
0 [[120,  19],     
1  [ 24,  60]]



In [39]:
from sklearn.metrics import classification_report,confusion_matrix

In [38]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.86      0.85       139
           1       0.76      0.71      0.74        84

    accuracy                           0.81       223
   macro avg       0.80      0.79      0.79       223
weighted avg       0.81      0.81      0.81       223



In [42]:
print(confusion_matrix(y_test)

[[120  19]
 [ 24  60]]


In [ ]:
  PRECISON(0)  =  TP / (TP + FN)
    
            = 120 / 120 + 24
        
            =  0.83

In [ ]:
  PRECISION(1)  =  TP / TP +FN
    
    
                     60
    
                    ______
                   60+19
            
                  = 0.76
        
            

In [ ]:
[120  19]
 [ 24  60]


RECALL (0) = TP

           ______
    
    
           TP+ FP
        
        
         = 120 / 120 +19
            
         = 0.86
        
        
        TP / TP/TN

In [ ]:
RECALL (1) = TP

         _ _____
    
    
           TP+ FP
        
        
         = 60 / 60 + 24
            
         = 60/84
        
        = 0.71